apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    isDefault: true
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    url: http://localhost:9090
    jsonData:
      httpMethod: POST
      manageAlerts: false
      prometheusVersion: "2.41.0"
      prometheusType: "Prometheus"